### ISSUE TITLE
Documentation: Migrating from --𝚎𝚡𝚙𝚎𝚛𝚒𝚖𝚎𝚗𝚝𝚊𝚕-𝚖𝚘𝚍𝚞𝚕𝚎𝚜 — Discrepancies and Considerations

### ISSUE THREAD

**Issue by SMotaal** [nodejs/ecmascript-modules#16]
This issue is intended to track a list of aspects destined to live in a "Migrating from --𝚎𝚡𝚙𝚎𝚛𝚒𝚖𝚎𝚗𝚝𝚊𝚕-𝚖𝚘𝚍𝚞𝚕𝚎𝚜 — Discrepancies and Considerations" document. Those are a shortlist of features which users relied on previously to address certain problems for which the new implementation either offers a more robust alternative or otherwise.

- [ ] Default handling of `index.mjs` inside and outside of <kbd>ESM Package Scope</kbd>
   - TBD

**Comment by Trott** [comment]
@nodejs/modules-active-members Should this issue be moved to the main node repo or closed?

**Comment by MylesBorins** [comment]
I think it can be closed
