### ISSUE TITLE
Type Error: Method Map… incompatible receiver (with --expose-internals)

### ISSUE THREAD

**Issue by SMotaal** [nodejs/ecmascript-modules#21]
This issue has been nagging at me for a few months and until now it seemed to be only scoped to <samp>--experimental-vm-modules</samp> but that is no longer true.

**Versions**: 11.4.0 and [irp-implementation](https://github.com/guybedford/node/tree/irp-implementation)

**How to reproduce**

1. Create a folder with a simple `esm.mjs` (and `esm.js` for irp-implementation):

   > ```js
   > export default 'esm is awesome';
   > ```

   *Note*: for irp-implementation you may need a `package.json` with ESM features in the current folder or the first parent folder with a `package.json`:

   > ```json
   > {
   >     "exports": {}
   > }

2. Run node as follows with your respective esm entry:
   
   ```sc
   $ node --experimental-vm-modules --expose-internals --experimental-modules esm.mjs
   ```
   
   make sure to drop <samp>--experimental-vm-modules</samp> and <samp>--experimental-modules</samp> for irp-implementation as follows:
   
   ```sc
   $ node --expose-internals esm.js
   ```

3. Expected output will include:
   
   ```red
   TypeError: Method Map.prototype.has called on incompatible receiver [object Object]
       at Proxy.has (<anonymous>)
       at Loader.getModuleJob (internal/modules/esm/loader.js:132:24)
       at process._tickCallback (internal/process/next_tick.js:43:7)
       at executeUserCode (internal/bootstrap/node.js:317:13)
       at startExecution (internal/bootstrap/node.js:242:3)
       at startup (internal/bootstrap/node.js:193:3)
       at internal/bootstrap/node.js:692:1
   error Command failed with exit code 1.
   ```

**Comment by ljharb** [comment]
Proxies don't forward internal slots; so if we're using a Proxy to wrap language values that have internal slots then we're going to have some observable problems as a result.

**Comment by devsnek** [comment]
this error came from a file in `lib/internal/vm` that was doing `module.exports = new Map()`. the file doesn't exist anymore, and i'm making sure we don't use this pattern anymore. i think this can be closed.

**Comment by SMotaal** [comment]
So just to clarify and specifically for the [irp-implementation](https://github.com/guybedford/node/tree/irp-implementation) where this can still be reproduced, what do we need to port to resolve this there as well?

**Comment by devsnek** [comment]
@SMotaal you'd need to remove any instances of `module.exports = someBuiltinWithInternalSlots`. in `/lib`

**Comment by jkrems** [comment]
@devsnek So the problem is likely that the module map uses `module.exports = MODULE_MAP` or something?

**Comment by devsnek** [comment]
@jkrems i haven't looked at the irp thing (when @SMotaal opened this issue was the first i had heard of it) so i can't really say for sure where the problem is.

**Comment by SMotaal** [comment]
I think it originates from [internal/vm/source_text_module.js#L267-L272](/guybedford/node/blob/irp-implementation/lib/internal/vm/source_text_module.js#L267-L272)

```js
module.exports = {
  SourceTextModule,
  wrapToModuleMap,
  wrapMap,
  linkingStatusMap,
};
```

**Comment by SMotaal** [comment]
@devsnek I did a quick search and found:

- Both `linkingStatusMap` and `wrapMap` appear on master in [lib/vm.js#L93-L114](https://github.com/nodejs/node/blob/master/lib/vm.js#L93-L114)

- `wrapToModuleMap` appears on master in [lib/internal/process/esm_loader.js#L11-L36](https://github.com/nodejs/node/blob/master/lib/internal/process/esm_loader.js#L11-L36)

**Comment by devsnek** [comment]
@SMotaal no, this only applies if `module.exports` itself is an object with internal slots. when esm is enabled, we transform all builtin `module.exports` into proxies so we can simulate `export let` when APMs modify the cjs version

**Comment by SMotaal** [comment]
I appreciate your unique insights on this obviously 👍

**Comment by guybedford** [comment]
The problem seems to come from `lib/internal/modules/esm/translators.js` where that does `module.exports = new Map()`.

Instead I'm going to switch that map to be a named export in the irp-implementation. Not sure why this is just coming up in our branch though.

**Comment by guybedford** [comment]
I can confirm the above fix works and have implemented this in the irp-implementation branch that @SMotaal was posting for here.
