### ISSUE TITLE
TODO: Support dual CommonJS/ESM packages

### ISSUE THREAD

**Issue by GeoffreyBooth** [nodejs/ecmascript-modules#36]
This is an issue so that we don’t forget to add support for packages that can be both `require`d into CommonJS and `import`ed into ESM, as native CommonJS or ESM packages in each mode (a.k.a. “dual-mode” packages).

Mentioned in https://github.com/nodejs/ecmascript-modules/pull/35#discussion_r257476520 and https://github.com/nodejs/ecmascript-modules/pull/32#issuecomment-462407469 as a TODO item to address.

**Comment by ljharb** [comment]
I prefer the mechanism for this to be extension lookup; I'm not aware of any less complex possibilities.

**Comment by balupton** [comment]
From the discussions years ago, extension look ups seem the best option.

As an aside, https://editions.bevry.me and https://discuss.bevry.me/t/how-bevry-automates-maintenance-of-its-prolific-open-source-portfolio/693?u=balupton may be useful resource for people looking into publishing both, as Bevry already does this.

**Comment by Trott** [comment]
Is this an issue that should be transferred to the main repository at this time? Or perhaps simply closed?

**Comment by MylesBorins** [comment]
Can be closed imho
