### ISSUE TITLE
Missing documentation for IRP modules

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/ecmascript-modules#42]
The changes for IRP based modules did not come with documentation. Is there a plan to document and update esm.md soon?

**Comment by guybedford** [comment]
Certainly documentation should be fleshed out prior to upstreaming. The initial focus has been on keeping the spec up-to-date.

**Comment by GeoffreyBooth** [comment]
I’ll update the docs, @guybedford will update the spec.

**Comment by ljharb** [comment]
What is “IRP”?

**Comment by GeoffreyBooth** [comment]
> What is “IRP”?

It’s https://github.com/GeoffreyBooth/node-import-file-specifier-resolution-proposal/. I don’t know how people got the initialism IRP out of that, but that’s what they’re referring to.

**Comment by weswigham** [comment]
__I__ mport __R__ esolution __P__ roposal I believe

**Comment by GeoffreyBooth** [comment]
> **I** mport **R** esolution **P** roposal I believe

Yeah it was a poorly named proposal 😄
