### ISSUE TITLE
Throw error when conflicting type params are passed

### ISSUE THREAD

**Issue by ljharb** [nodejs/ecmascript-modules#56]
Per https://github.com/nodejs/ecmascript-modules/pull/55#issuecomment-471154323

An error should be thrown if:
 - more than one `--type` is passed
 - any alias for a `--type` value is passed along with any `--type` value
 - multiple aliases for a `--type` value are passed

**Comment by GeoffreyBooth** [comment]
Examples:

```sh
node --experimental-modules --type=commonjs --type=module file.js
node --experimental-modules --type=commonjs -m file.js
```

**Comment by devsnek** [comment]
getting rid of `-m` would help so that its more obvious when you've duplicated the flag.

aside from that, node in general just allows duplicated flags.
```
node --title=1 --title=2
> process.title
'2'
```

**Comment by ljharb** [comment]
@devsnek allowing duplicate flags isn’t necessary to allow overriding; but it may be that node’s options parser lacks the capability to properly distinguish them.

**Comment by devsnek** [comment]
@ljharb my point is more that this isn't an issue specific to `--type` (although `-m` is unique in that its the only short flag which can "disagree" with a longer flag). perhaps someone could raise this issue upstream?

**Comment by GeoffreyBooth** [comment]
cc @addaleax

**Comment by GeoffreyBooth** [comment]
Resolved in https://github.com/nodejs/ecmascript-modules/pull/45
